# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 07:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gym_app', '0003_class_day'),
    ]

    operations = [
        migrations.CreateModel(
            name='NewClass',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
