# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 07:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gym_app', '0004_newclass'),
    ]

    operations = [
        migrations.AddField(
            model_name='class',
            name='costam',
            field=models.CharField(default='2', max_length=20),
            preserve_default=False,
        ),
    ]
