# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 07:37
from __future__ import unicode_literals

import datetime

from django.db import migrations, models
from django.utils.timezone import utc


class Migration(migrations.Migration):
    dependencies = [
        ('Gym_app', '0005_class_costam'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='class',
            name='costam',
        ),
        migrations.AddField(
            model_name='creditcard',
            name='number',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='security_code',
            field=models.IntegerField(default=1),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='creditcard',
            name='valid_through',
            field=models.DateTimeField(default=datetime.datetime(2016, 11, 18, 7, 37, 39, 910000, tzinfo=utc)),
            preserve_default=False,
        ),
    ]
