# -*- coding: utf-8 -*-
# Generated by Django 1.9.5 on 2016-11-18 07:47
from __future__ import unicode_literals

import datetime

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('Gym_app', '0006_auto_20161118_0837'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NewClass',
        ),
        migrations.AddField(
            model_name='class',
            name='end_time',
            field=models.TimeField(default=datetime.time(13, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='class',
            name='start_time',
            field=models.TimeField(default=datetime.time(12, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='classinformation',
            name='description',
            field=models.TextField(default='sample description.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='description',
            field=models.TextField(default='sample description2'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='exercise',
            name='url',
            field=models.URLField(default='http://www.myurl.com'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalrecord',
            name='time',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='goalrecord',
            name='value',
            field=models.FloatField(default=7),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='last_purchase',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 0, 0)),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='membershipcard',
            name='valid_through',
            field=models.DateTimeField(default=datetime.datetime(2016, 12, 11, 0, 0)),
            preserve_default=False,
        ),
    ]
